name: Daily Contribution

on:
  schedule:
    - cron: "30 5 * * *"   # Runs daily at 11:00 AM IST
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update activity file
        run: |
          echo "Last updated: $(date -u)" > last-updated.txt

      - name: Commit changes
        run: |
          git config user.name "Anushrikva"
          git config user.email "anushriraj16@gmail.com"
          git add last-updated.txt
          git commit -m "chore: update activity"
          git push
